In [3]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# XOR Input
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# XOR Output
y = np.array([0, 1, 1, 0])

# Create Multi-Layer Perceptron
# One hidden layer with two neurons
model = MLPClassifier(
    hidden_layer_sizes=(2,),
    activation='logistic',
    solver='lbfgs',
    max_iter=1000,
    random_state=42
)

# Train the model
model.fit(X, y)

# Predict
y_pred = model.predict(X)

# Display Results
print("Input:")
print(X)

print("\nActual Output:")
print(y)

print("\nPredicted Output:")
print(y_pred)

print("\nAccuracy: {:.2f}%".format(accuracy_score(y, y_pred) * 100))

Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Actual Output:
[0 1 1 0]

Predicted Output:
[1 1 1 0]

Accuracy: 75.00%
