In [1]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

# XOR Input
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# XOR Output
y = np.array([0, 1, 1, 0])

# Create Single Perceptron
model = Perceptron(max_iter=1000, random_state=42)

# Train the model
model.fit(X, y)

# Predict
y_pred = model.predict(X)

# Display Results
print("Input:")
print(X)

print("\nActual Output:")
print(y)

print("\nPredicted Output:")
print(y_pred)

print("\nAccuracy:", accuracy_score(y, y_pred) * 100, "%")

Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Actual Output:
[0 1 1 0]

Predicted Output:
[0 0 0 0]

Accuracy: 50.0 %
